name: CI Release Draft

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "!**/readme.md"

permissions:
  contents: write
  pull-requests: write

jobs:
  draft-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"